site_name: My Markdown Test

theme:
  name: material
  repo_url: https://github.com/nivincent/MarkdownMaterial
  repo: fontawesome/brands/github
  repo_name: nivincent/MarkdownMaterial
  edit_uri: edit/main/docs/
  icon:
    edit: material/pencil
    view: material/eye
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: slate
      primary: green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: default
      primary: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

features:
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.tracking
  - navigation.expand
  - navigation.prune
  - toc.integrate
  - navigation.top
  - search.suggest
  - search.highlight
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  - content.action.edit
  - content.action.view

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
